# Generated by Django 5.1.3 on 2024-12-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название локации')),
                ('adress', models.CharField(max_length=50, verbose_name='Адрес локации')),
                ('district', models.CharField(max_length=25, verbose_name='Район/Г.О. локации')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
    ]
