# Generated by Django 5.1.3 on 2024-12-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='location',
            name='district',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, help_text='Полный адрес локации', null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Например: Дрожжино, Боброво и т.д.', max_length=255, verbose_name='Название локации'),
        ),
    ]
