# Generated by Django 5.1.3 on 2024-12-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_options_remove_location_adress_and_more'),
        ('usersroles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='linked_locations',
            field=models.ManyToManyField(related_name='staff', to='location.location', verbose_name='Закрепленные локации для работы'),
        ),
    ]
