# Generated by Django 5.1.3 on 2024-12-24 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('location', '0002_alter_location_options_remove_location_adress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='linked_location',
        ),
        migrations.AddField(
            model_name='child',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='location.location', verbose_name='Локация обучения'),
        ),
        migrations.AddField(
            model_name='parent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parents', to='location.location', verbose_name='Локация'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
