# Generated by Django 5.1.3 on 2025-02-18 10:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_parent_is_active'),
        ('location', '0002_alter_location_options_remove_location_adress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('schedule', models.TextField(help_text='Пример: Пн/Ср/Пт 18:00-20:00', verbose_name='Расписание')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='Дата первого занятия группы', verbose_name='Дата начала')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('archive', 'Архивная')], default='active', help_text='Активные группы отображаются в общем списке', max_length=10, verbose_name='Статус группы')),
                ('location', models.ForeignKey(help_text='Выберите локацию из списка', on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='location.location', verbose_name='Локация')),
                ('students', models.ManyToManyField(blank=True, help_text='Выберите учеников для этой группы', related_name='groups', to='clients.child', verbose_name='Ученики')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'indexes': [models.Index(fields=['status', 'start_date'], name='groups_grou_status_254dc1_idx')],
            },
        ),
    ]
